version: '2'
services:
  radagast-app:
    image: radagast
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://radagast-postgresql:5432/Radagast
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 9876:9876
  radagast-postgresql:
    extends:
      file: postgresql.yml
      service: radagast-postgresql
